config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :goals, only: [:show]
  end
  resource :session
  resources :goals, except: [:show]
  resources :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true

  validates :body, presence: true
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :text             not null
#  user_id     :integer          not null
#  status      :string           default("Incomplete"), not null
#  permission  :string           default("Public"), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Goal < ActiveRecord::Base
  validates :title, :description, :user_id, :status, :permission, presence: true
  validates :status, inclusion: { in: ["Complete", "Incomplete"] }
  validates :permission, inclusion: { in: ["Private", "Public"] }

  belongs_to :user
  has_many :comments, as: :commentable

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}
  after_initialize :ensure_session_token

  attr_reader :password

  has_many :goals, dependent: :destroy
  has_many :comments, as: :commentable
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username,password)
    user = User.find_by(username: username)
    return nil unless user && user.is_password?(password)
    user
  end

  def completed_goals
    self.goals.where(status: "Complete")
  end

  def incomplete_goals
    self.goals.where(status: "Incomplete")
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  def generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?, :valid_author?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_in(user)
    session[:session_token] = user.reset_session_token!
  end

  def sign_out
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def valid_author?
    params[:id].to_i == current_user.id
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create

  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :validate_author, only: :show

  def show
    @goal = Goal.find(params[:id])

  end

  def validate_author
    user = User.find(params[:user_id])
    redirect_to user_url(user) unless user.id == current_user.id
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
            params[:user][:username],
            params[:user][:password]
            )
    if user
      sign_in(user)
      redirect_to user_url(user)
    else
      flash.now[:base] = "Invalid error credentials"
      render :new
    end
  end

  def destroy
    sign_out
    render :new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signed_in, only: :show

  def new
    render :new
  end

  def show
    User.includes(:goals)
    @user = User.find(params[:id])
    render :show
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:base] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

  def require_signed_in
    redirect_to new_session_url unless signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'>".html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/show.html.erb
<h1> <%= @goal.title %> </h1>
<h2><b>STATUS:</b><%= @goal.status %></h2>
<h3> Made by: <%= @goal.user.username %> </h3>
<h3> Description: <%= @goal.description %> </h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash[:base] %>

<% if signed_in? %>
Signed in as: <%= current_user.username %>
<%= button_to "Sign Out", session_url, method: :delete %>
<% else %>
  <%= link_to "Sign in!", new_session_url %>
  <%= link_to "Sign up!", new_user_url  %>
<%end%>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form  action="<%= users_url %>" method="post">
  <%= auth_token %>
  <label for="user_username">
    Username
    <input id="user_username" type="text" name="user[username]">
  </label>

  <label for="user_password">
    Password
    <input id="user_password" type="password" name="user[password]">
  </label>

  <input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<h1>Welcome to the Goals App Page</h1>

<h3> Here are the goals for <%= @user.username %>! </h3>

<h4> Incomplete Goals: </h4>
<ol>
<% @user.incomplete_goals.each do |goal| %>
<li><b><%= goal.title %></b>, created at: <%= goal.created_at.to_date %>
  <% if valid_author? || goal.permission == 'Public'  %>
    <br>
    <%= goal.description[2..35] +"...  " %>
    <%= link_to "See more", user_goal_url(@user, goal), class: "SeeMore"  %>
  <% end %>
</li>
<br>
<% end %>
</ol>

<h4> Complete Goals: </h4>

<% @user.completed_goals.each do |goal| %>
&#10003; <b> <%= goal.title  %></b>
<br>
<% end %>

<h4> Comments: </h4>
<% @user.comments.each do |c|%>
Author: <%= c.user_id %><br>
Body:  <%= c.body %>
<% end%>

<h4> Add Comment </h4>

<form  action="<%= comments_url %>" method="post">
  <%= auth_token %>

  <label for="comment_body">
    Comment
    <input id="comment_body" type="text" name="comment[body]">
  </label>

  <input type="submit" value="Add Comment">
</form>